name: Build Images
on:
  push:
    branches: main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Login Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
#      - name: Build AMD64 Image
#        run: |
#          docker build -t jamielsharief/mysql:amd64 --build-arg ARCH=amd64/ .
#          docker push jamielsharief/mysql:amd64
#      - name: Build ARM64 Image
#        run: |
#          docker build -t jamielsharief/mysql:arm64 --build-arg ARCH=arm64v8/ .
#          docker push jamielsharief/mysql:arm64
#      - name: Create & Upload Manifest
#        env:
#          DOCKER_CLI_EXPERIMENTAL: enabled
#        run: |
#          docker manifest create \
#          jamielsharief/mysql:latest \
#          --amend jamielsharief/mysql:amd64 \
#          --amend jamielsharief/mysql:arm64
#          docker manifest push jamielsharief/mysql:latest
#         End of manifesto method
      - name: Install buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v1
        with:
          version: latest
#     linux/arm/v7 error: failed to solve: rpc error: code = Unknown desc = executor failed running
      - name: Build Images
        run: |
          docker buildx build --platform linux/arm64,linux/amd64 --tag jamielsharief/mysql:latest --push .